---
# Wolters Kluwer Backstage compliant catalog info
# See https://backstage.io/docs/features/software-catalog/descriptor-format
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: laminas-mime
  description: "Create and parse MIME messages and parts"
  annotations:
    wolterskluwer.io/bit-id: '041800002496'
spec:
  type: library
  lifecycle: support
  owner: Glenn.Van-Den-Broeck@wolterskluwer.com
